export const creators = [
  'Algayné Varga Éva (VFG)',
  'Balázs Ildikó Erzsébet (VFG)',
  'Drávucz Anita (VFG)',
  'Kiss Béla (VFG)',
  'Lapu Béla (VFG)',
  'Pécsi István (VFG)',
  'Pécsiné Röhri Zsuzsanna (VFG)',
  'Pogány Gyula (VFG)',
  'Somogyi  Tamás (VFG)',
  'Szarvas Natália (VFG)',
  'Szepesi Tibor (ELTE)',
  'Szepesi Zoltán (IBM)',
  'Tekse Mariann (VFG)',
  'Veres Dénes (VFG)',
]
