export const creators = [
  'Algayné Varga Éva (VFG)',
  'Balázs Ildikó (VFG)',
  'Baloghné Cseh Judit (VKG)',
  'Dénes Gergő (VFG)',
  'Drávucz Anita (VFG)',
  'Fekete Bálint (VFG)',
  'Forgács Kata (VFG)',
  'Gál Bence (VKG)',
  'Kiss Béla (VFG)',
  'Lapu Béla (VFG)',
  'Medvegy Gábor (VKG)',
  'Pécsi István (VFG)',
  'Pécsiné Röhri Zsuzsanna (VFG)',
  'Pogány Gyula (VFG)',
  'Somogyi  Tamás (VFG)',
  'Szarvas Natália (VFG)',
  'Szepesi Zoltán (BME)',
  'Veres Dénes (VFG)',
]
